<?php

//
// defines user some default access right constants, which are used in
// the $NIOLO->CheckAccess() and ThemeMenu->AddUserOption() methods.
//

// all defs in english please !!!
define('A_SYSTEM',    'system');
define('A_ADMIN',     'admin');
define('A_ACCESS',    'access');
define('A_INSERT',    'insert');
define('A_DELETE',    'delete');
define('A_UPDATE',    'update');
define('A_QUERY',     'query');
define('A_EXECUTE',   'execute');
define('A_DEVELOP',   'develop');

// verify usage of following definitions
// and change to new defs 
define('A_ACESSO',    'acesso');
define('A_INSERIR',   'inserir');
define('A_EXCLUIR',   'excluir');
define('A_CONSULTAR', 'consultar');
define('A_ALTERAR',   'alterar');
define('A_PROCESSAR', 'processar');
define('A_DEVELOP',   'develop');

?>
