<?php
global $MIOLOCONF;

// TUTORIAL DB Config
$MIOLOCONF['DB']['wiki']['system']   = 'postgres';
$MIOLOCONF['DB']['wiki']['host']     = '127.0.0.1';
$MIOLOCONF['DB']['wiki']['name']     = 'wiki';
$MIOLOCONF['DB']['wiki']['user']     = 'postgres';
$MIOLOCONF['DB']['wiki']['password'] = 'REDACTED';

?>

