<?php
global $MIOLOCONF;

// TUTORIAL DB Config
$MIOLOCONF['DB']['tutorial']['system']     = 'postgres';
$MIOLOCONF['DB']['tutorial']['host']       = '127.0.0.1';
$MIOLOCONF['DB']['tutorial']['name']       = 'tutorial';
$MIOLOCONF['DB']['tutorial']['user']       = 'postgres';
$MIOLOCONF['DB']['tutorial']['password']   = 'REDACTED';

?>
