<?php
//theme settings
$MIOLOCONF['theme']['main']      = 'vestibular';
$MIOLOCONF['theme']['lookup']    = 'vestibular';
$MIOLOCONF['theme']['title']     = 'UFJF - Programas de Ingresso';

$MIOLOCONF['login']['check']               = false;

//$MIOLOCONF['trace_port'] = 9999;

/*
$MIOLOCONF['DB']['ingresso']['system']   = 'firebird';
$MIOLOCONF['DB']['ingresso']['host']     = '127.0.0.1';
$MIOLOCONF['DB']['ingresso']['name']     = 'e:\miolo\miolo2\modules\vestibular\sql\ingresso.fdb';
$MIOLOCONF['DB']['ingresso']['user']     = 'dbuser';
$MIOLOCONF['DB']['ingresso']['password'] = 'REDACTED';
*/

$MIOLOCONF['DB']['ingresso']['system']   = 'oracle8';
$MIOLOCONF['DB']['ingresso']['host']     = 'dbhost.example.edu.br';
$MIOLOCONF['DB']['ingresso']['name']     = 'exampledb';
$MIOLOCONF['DB']['ingresso']['user']     = 'dbuser';
$MIOLOCONF['DB']['ingresso']['password'] = 'REDACTED'; 
?>