#!/bin/sh
#
# Script para criação das Bases e Tabelas do MIOLO
# Script for creating Base and Tables
#
# Author: Vilson Cristiano Gartner - vilson@miolo.org.br
# Updated: 27 Aug. 2004
#

if [ $1 ]; then
    echo "- Creating database 'bis'..."
    su postgres -c "$1/createdb bis"
    
    echo
    echo "- Creating tables and inserting data..."
    su postgres -c "$1/psql -c '\i miolo/modules/common/sql/bis-pgsql.sql' -d bis"
else
    echo "MISSING ARGUMENT 1"
fi
