#!/bin/sh
#
# Script para criação das Bases e Tabelas do MIOLO
# Script to update MIOLO's Base and Tables
#
# Author: Vilson Cristiano Gartner - vilson@miolo.org.br
# Date: 27 Aug. 2004
#

if [ $1 ]; then
    echo
    echo "- Aplying table changes..."
    su postgres -c "$1/psql -c '\i miolo/modules/common/sql/sqlchanges-pgsql-final.sql' -d bis"
else
    echo "MISSING ARGUMENT 1 - Base not updated"
fi
